name: flutter_reflective_screensaver
description: This package mimics the standby animation of a Digital Versatile Disk
version: 0.0.12
homepage: https://github.com/fen0268/FlutterreFlectiveScreensaver

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
